#! /bin/bash


# stage1 settings -------------------------------------------------------------

stage=stage1
src_path=${_ROOT}/src/${github_path}/${llvm_version}
obj_path=${_ROOT}/obj/${github_path}/${llvm_version}/${stage}

stage1_cmake_file=${_ROOT}/etc/${stage}.cmake
stage1_build_dir=${obj_path}/build
stage1_target_dir=${obj_path}/target


# stage2 settings -------------------------------------------------------------

stage=stage2
src_path=${_ROOT}/src/${github_path}/${llvm_version}
obj_path=${_ROOT}/obj/${github_path}/${llvm_version}/${stage}

stage1_target_dir=${obj_path/stage2/stage1}/target
stage1_build_dir=${obj_path/stage2/stage1}/build

stage2_cmake_file=${_ROOT}/etc/${stage}.cmake
stage2_build_dir=${obj_path}/build
stage2_target_dir=${obj_path}/target


# stage3 settings -------------------------------------------------------------

stage=stage3
src_path=${_ROOT}/src/${github_path}/${llvm_version}
obj_path=${_ROOT}/obj/${github_path}/${llvm_version}/${stage}

stage2_target_dir=${obj_path/stage3/stage2}/target
stage2_build_dir=${obj_path/stage3/stage2}/build

stage3_cmake_file=${_ROOT}/etc/${stage}.cmake
stage3_build_dir=${obj_path}/build
stage3_target_dir=${obj_path}/target


